# Project information
site_name: ScratchHW
site_url: https://ScratchHW.github.io/wiki-zh
site_author: ScratchHW Team
site_description: >-
  Porgram your hardware with scratch3

# Repository
repo_name: ScratchHW/wiki-zh
repo_url: https://github.com/ScratchHW/wiki-zh

# Configuration
theme:
  name: material
  language: zh
  features:
    - navigation.tabs

# Copyright
copyright: Copyright &copy; 2020 ScratchHW

# Customization
extra:
  disqus: scratchhw

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ScratchHW

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
nav:
  - 主页: index.md
  - 入门:
    - 安装(开发者): install-software-developer.md
    - 安装(普通用户)): install-software-user.md
    - 许可证: license.md
  - 指南:
    - 构架介绍: reference/framework-introduction.md
  - 变更记录:
    - 发行说明: changelog.md